---

# Unix users to create. All users defined here are root users (access
# to docker as well as wheel).
users:
  - mxs
  - faltad
  - ironzorg
  - notoriouspig

# Domains & services to manage.
#
# Config:
#
# - domain: domain for which to generate an SSL certificate,
# - type: template configuration used the generate the config.
#
# Other entries are directly passed to the template configuration.
websites:

  - domain: neuromancer.sbrk.org
    template_config: static.skeleton
    data: /srv/http/neuromancer.sbrk.org/public

  - domain: blz.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10001

  - domain: sandwalker.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10002

  - domain: mxs.sbrk.org
    template_config: proxy_local_port_with_landing.skeleton
    local_port: 10003
    landing_port: 10004
    landing_static: highlander

  - domain: landing.mxs.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10004

  - domain: detours.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10005

  - domain: data.mxs.sbrk.org
    template_config: proxy_local_port.skeleton
    local_port: 10006
