---

- name: set up virtualhost main directory
  file:
    owner: http
    path: "/srv/http/{{ item.domain }}"
    state: directory
    mode: 0755
  loop: "{{ websites }}"

- name: set up virtualhost log directory
  file:
    owner: http
    path: "/srv/http/{{ item.domain }}/log"
    state: directory
    mode: 0750
  loop: "{{ websites }}"

- name: set up virtualhosts
  template:
    owner: http
    src: "templates/{{ item.template_config }}"
    dest: "/srv/http/{{ item.domain }}/nginx.conf"
  loop: "{{ websites }}"

- name: enable virtualhost
  file:
    src: "/srv/http/{{ item.domain }}/nginx.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.domain }}.conf"
    owner: http
    group: http
    state: link
  loop: "{{ websites }}"
