---

- name: create unix users
  user: name="{{ item }}" append=yes state=present createhome=yes groups=sudo
  loop: "{{ users }}"

- name: set up ssh authorized keys
  authorized_key: user="{{ item }}" key="{{ lookup('file', 'files/user-' + item + '.pub') }}"
  loop: "{{ users }}"

- name: enable systemd lingering for users
  ansible.builtin.file:
    path: /var/lib/systemd/linger/{{ item }}
    state: touch
    mode: 644
    owner: root
    group: root
  loop: "{{ users }}"
