---

- name: set up standard packages
  apt:
    state: present
    pkg:
      - htop
      - emacs-nox
      - docker
      - docker-compose
      - nginx
      - certbot
      - python3-certbot-nginx
      - hugo
      - lsof
      - mosh
      - tmux
      - zsh
      - kakoune
      - kitty-terminfo

