---

- name: set up standard packages
  apt:
    pkg:
      - htop
      - emacs-nox
      - docker
      - docker-compose
      - nginx
      - certbot
      - python3-certbot-nginx
      - hugo
      - lsof
