---

- name: install the package dependencies for Wireguard
  apt:
    state: present
    pkg:
      - wireguard
      - wireguard-tools

- name: enabling IPv4 forwarding
  ansible.posix.sysctl:
    name: "net.ipv4.ip_forward"
    value: 1
    state: present
    sysctl_set: yes

- name: enabling IPv6 forwarding
  ansible.posix.sysctl:
    name: "net.ipv6.conf.all.forwarding"
    value: 1
    state: present
    sysctl_set: yes
